apiVersion: v1
kind: Service
metadata:
  name: eusuite-login
  namespace: eucloud
spec:
  type: NodePort
  selector:
    app: eusuite-login
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
