apiVersion: v1
kind: Service
metadata:
  name: eumail-frontend
  namespace: eucloud
  labels:
    app: eumail-frontend
spec:
  type: NodePort
  selector:
    app: eumail-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
      protocol: TCP
