apiVersion: v1
kind: Service
metadata:
  name: eumail-backend
  namespace: eucloud
  labels:
    app: eumail-backend
spec:
  type: NodePort
  selector:
    app: eumail-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30510
      protocol: TCP
