apiVersion: v1
kind: Service
metadata:
  name: eucloud-frontend
  namespace: eucloud
spec:
  type: NodePort
  selector:
    app: eucloud-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
