apiVersion: v1
kind: Service
metadata:
  name: eugroups-frontend
  namespace: eucloud
  labels:
    app: eugroups-frontend
spec:
  type: NodePort
  selector:
    app: eugroups-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30083
      protocol: TCP
