apiVersion: v1
kind: Service
metadata:
  name: euadmin-backend
  namespace: eucloud
  labels:
    app: euadmin-backend
spec:
  type: NodePort
  selector:
    app: euadmin-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30095
      protocol: TCP
